sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
gemfile:
- docs/Gemfile

install:
  # Install Jekyll and dependencies
  - bundle install

script:
  - chmod +x deploy.sh
  - "./deploy.sh"

branches:
  only:
  - master